language: rust
sudo: required
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=kicad_parse_gen/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: K2rSTsVLWOrXlevzTd2L0coPmxyQ0swQDp5nWSbyBTDkhSfqlRWRtUG8GoX9kueGaJrz+xYLkAURQfIqOoFyAz9HgvMMOZtGNfkMrLhJ6PtyP4ZZzEXsaEWp0kGRBe09gPmtIos/QykkP+jzouokiQOaYQ9SofLU/oLxUZQQGFPImy20f+MyPa6Iwj+mjNDV2FEObFl6uLPYabuwnmNh6jRmaf+HCp2EIrlT81Bj4vDy7DPn76Y1oE2P6Os1Zc3I1nxU0QEC73c8FOJ+o+NdfhNnmifDDeMMf2kw/YLlU+zslYmk7S/GP2ZwSep8sPp4o027prU8KByuoGUgzKKq8YdScUrXd5PmEhJgx4JOdGHyOsndQd06xFlTWp+O8vF/mBpUSzUDFSaGjC4Mcpb38hcbyiFvnN/VdjsRdyM1pTWwY3gxTE+Z4dWeVpZIsYRpLm9xPMBPggLwAxks0gd4HdBXfishP+V+A2wooVjXFCLZkdnm2i8h2aTTx7EKqyxUZbiE7FEQeoeOWw5GQzXrDeYNzc+Nel2N+1LgevpPS3QDfV6Vvl4JKmnrJ/q5LI1L8MZAmMX5ICxcsLHEcD/y+4glJJZ2nuKI9NcE0lYYyI6eCgVHuB3IReWzSgPHWiFuYYHnl95JTOatZGXFFIcbINnvjFSAf6WOedOaMYygxY8=
