language: rust
sudo: required
after_success: |
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      cargo doc &&
      echo "<meta http-equiv=refresh content=0;url=kicad_parse_gen/index.html>" > target/doc/index.html &&
      sudo pip install ghp-import &&
      ghp-import -n target/doc &&
      git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
      global:
              secure: vzgy/uWGCQIktNBBzSGxDZaICU0aWK7Yebfa46aYWIQ4tUZdGGEXPlIrtuvxBW6zI+e2MMcNa3eB4MwaceoLT7DxwMPP1SuoPsdNZdu4U9bXZOWJelFD4Bue0YgPaghD0OzY0Oh88rj7bHSJFARbc9I2T/JpGVCbj/cQKHxlrs9FFO70PaLpB4ech4siU6iHU5hw3lvPG5tKzg3IniheMrjw6TxXLT1uvhbGUpxuUEGlo6Nt+U5WE4mw56Yqy2ILUYkhjbkADBcSte638vQT4ShY0CtCcjXxSsfGrqNdayQHlZNgLa1aroY+3bIA0X0veQ44XRxhLEgJalnZ3RHlcRgtglLX7LArdw17ClmgOt33hsv9vdJmIu1IBW9jtS+AQ781pobcvPA86DBRbymssZgP9vFUOAkYtq3xHpfmK5s+OCazIA/iPQMpaLdKT50k5SvrVU86rrUmuDxi6EJmEX88h2Y+h3AR+n4IOlO+7ZingRRJhG2ncqP2e2nOTdI2X3df1QrDpaAOYDpIP7yKqT17uLohI//c5cw1eVA4swRRo/gRqY8OppJmdR4OiYTI6Adp8zWbI1yVOKJCqvXd/27V318npPB8TMaoGAuWLaw6FnnIYM+sGPSZIXOPnUeynqfykHUSMlF4M3qOWFFbOupPG0ogRFaH6H+IIp7Zwvw=
