[package]
name = "rustykicad"
version = "0.3.1"
authors = ["Joost Damad <joost@productize.be>"]

[features]
use_clippy = ["clippy"]

[dependencies]
rustc-serialize = "0.3"
symbolic_expressions = "0.3.7"
clippy = { version = "0.*", optional = true }
