[package]
name = "rustykicad"
version = "0.3.1"
authors = ["Joost Damad <joost@productize.be>"]

[features]
nightly = []
nightly-testing = ["clippy", "nightly"]

[dependencies]
rustc-serialize = "0.3"
nom = "~1.2.0"
symbolic_expressions = "0.3.7"
clippy = { version = "0.*", optional = true }
