[package]
name = "kicad_parse_gen"
version = "0.5.3"
authors = ["Joost Damad <joost@productize.be>"]
license = "MIT"
repository = "https://github.com/productize/kicad-parse-gen"
documentation = "https://productize.github.io/kicad-parse-gen"

[dependencies]
rustc-serialize = "0.3"
symbolic_expressions = { git = "git://github.com/productize/symbolic-expressions.git" }
#symbolic_expressions = "0.3.11"
